trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: normal
        displayName: Normal Job
        steps:
          - script: echo This is step ONE
            displayName: 'Task 1'

          - script: echo This is step TWO 
            displayName: 'Task 2'

  - stage: 
    displayName: DeployToStaging
    jobs:
      - deployment: deploymentJob
        displayName: Deployment Job
        environment:
          name: Staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
           deploy:
             steps:
              - script: echo This is step ONE Deploy
                displayName: 'Deploy Task 1'

              - script: echo This is step TWO Deploy 
                displayName: 'Deploy Task 2'
